{{- if .Values.flink.applications.switch.streamProcess }}
{{- $application := .Values.application -}}
{{- $flinkVersion := .Values.flink.flinkVersion -}}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "stream-processing"
spec:
  flinkVersion: {{ $flinkVersion }}

  mavenCoordinate: com.dellemc.oe.flink.wordcount:stream-processing:{{ $application.mavenVersion }}
  mainClass: com.dellemc.oe.flink.wordcount.WordCountReader

  parallelism: {{ $application.defaultParallelism }}

  state: started

  parameters:
    - name: scope
      value: "{{ $application.pravega.pravega_scope }}"
    - name: input-stream
      value: "{{ $application.pravega.stream_name }}"
    - name: minNumSegments
      value: "3"

    # Flink Job Parameters
    - name: job.checkpointInterval
      value: "60000"
    - name: job.disableCheckpoint
      value: "false"
    - name: job.disableOperatorChaining
      value: "true"
    - name: rebalance
      value: "false"
{{- end }}
