{{- if .Values.flink.applications.switch.imageReader }}
{{- $flinkVersion := .Values.flinkVersion -}}
{{- $application := .Values.application -}}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "image-reader"
spec:
  flinkVersion: {{ $flinkVersion }}

  mavenCoordinate: com.dellemc.oe.readers:various-readers:{{ $application.mavenVersion }}
  mainClass: com.dellemc.oe.readers.ImageReader

  parallelism: {{ $application.defaultParallelism }}

  state: started

  parameters:
    - name: pravega_scope
      value: "{{ $application.pravega.pravega_scope }}"

    - name: stream_name
      value: "{{ $application.pravega.stream_name }}"

    - name: pravega_standalone
      value: "{{ $application.pravega.pravega_standalone }}"

    - name: pravega_controller_uri
      value:  "{{ $application.pravega.controller }}"

    - name: sourceParallelism
      value: "{{ $application.reader.parallelism }}"
{{- end }}

