# Chart should ONLY deploy the application and not all resources
onlyApplication: false

# Number of Projects to be created
projects: 1

# Number of Flink Clusters per project to be created
clusters: 1

# Number of Applications to be deployed per project
applications: 1


flink:
  applications:
    switch:
      jsonReader: true
      imageReader: false
      streamToStream: false
  flinkVersion: 1.10.1
  flinkImage: 1.10.1-2.12
# Detailed Project Control
project:
  zookeeperReplicas: 3
  mavenStorage: 20Gi
  localStorage: 20Gi

# Detailed FlinkCluster Control
cluster:
  localStorage: 20Gi
  taskManager:
    replicas: 2
    memory: 1024M
    cpu: 900m
    taskSlots: 5
    heap: 700m

# Detailed FlinkApplication Control
application:
  mavenVersion: 0.1.0
  defaultParallelism: 3

  pravega:
    pravega_scope: workshop-samples
    stream_name: json-stream


