# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
appParameters:

# These parameters are converted to JSON and then base-64 encoded.
appParametersJson: []


flinkVersion: 1.15.2

imageRef:
  name: flink-1.15.2

localStorage:
  replicas: 2
  size: 20Gi

#mainClass: Name of main class. REQUIRED.

volumes: [] 

parallelism: 3

jobManager:
  cpu: 1000m
  memory: 2048M
  replicas: 1
  heap: 1024m

taskManager:
  replicas: 1
  heap: 700m
  memory: 1300M
  cpu: 900m
  numberOfTaskSlots: 5

clusterConfiguration:
  restart-strategy.fixed-delay.delay: "30 s"
  taskmanager.memory.jvm-metaspace.size: "268435456"  # 256 Mi
  taskmanager.memory.task.off-heap.size: "0"
logging: {}
  #io.pravega: DEBUG
  #io.pravega.connectors: DEBUG
  #org.apache.flink: DEBUG
