#!/bin/bash
export PRAVEGA_CLIENT_AUTH_METHOD=Bearer
echo 'PRAVEGA_CLIENT_AUTH_METHOD :' $PRAVEGA_CLIENT_AUTH_METHOD
export PRAVEGA_CLIENT_AUTH_LOADDYNAMIC=true
echo 'PRAVEGA_CLIENT_AUTH_LOADDYNAMIC :' $PRAVEGA_CLIENT_AUTH_LOADDYNAMIC
export KEYCLOAK_SERVICE_ACCOUNT_FILE="/mnt/c/Projects/Nautilus/samples/beta1/workshop-samples/common/keycloak.json"
echo 'KEYCLOAK_SERVICE_ACCOUNT_FILE : ' $KEYCLOAK_SERVICE_ACCOUNT_FILE

# workshop Properties
export NAUTILUS_PROJECT_NAME=workshop-samples
echo 'NAUTILUS_PROJECT_NAME : ' $NAUTILUS_PROJECT_NAME
export PRAVEGA_SCOPE=workshop-samples
echo 'PRAVEGA_SCOPE : '$PRAVEGA_SCOPE
export STREAM_NAME=workshop-stream
echo 'STREAM_NAME : '$STREAM_NAME
export PRAVEGA_CONTROLLER_URI="tcp://10.240.126.45:9090"
echo 'PRAVEGA_CONTROLLER_URI : '$PRAVEGA_CONTROLLER_URI
